name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the React app with Webpack
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: npm run build

      - name: Verify dist folder exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "dist folder not found! Build failed."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
